import random

print(random.randint(1, 30))
#random float can be generated by multiplying random no with the range value
random_float=random.random()*8
#random floating no between 0 and 7.999999
print(random_float)
print(random.random())